apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: otel-cluster
  namespace: otel-system
spec:
  interval: 10m
  timeout: 5m
  chart:
    spec:
      chart: raw
      version: "2.0.0"
      sourceRef:
        kind: HelmRepository
        name: bedag
        namespace: flux-system
      interval: 5m
  releaseName: otel-cluster
  targetNamespace: otel-system
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  test:
    enable: false
  dependsOn:
    - name: otel-operator
      namespace: flux-system
  values:
    templates:
      - |
        apiVersion: opentelemetry.io/v1alpha1
        kind: OpenTelemetryCollector
        metadata:
          name: otel-cluster-events            
        spec:
          serviceAccount: otel-collector-cluster
          # image: otel/opentelemetry-collector-contrib:0.56.0
          mode: deployment
          env:
            - name: K8S_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: HUMIO_TOKEN_K8S_LOGS
              valueFrom:
                secretKeyRef:
                  name: infra-kubernetes-ingest-token
                  key: token
            - name: HUMIO_TOKEN_K8S_METRICS
              valueFrom:
                secretKeyRef:
                  name: metrics-kubernetes-ingest-token
                  key: token                  
          config: |
            exporters:
              otlphttp/k8s_logs:
                endpoint: https://${fqdn_ingest}/api/v1/ingest/otlp
                headers:
                  Authorization: Bearer $HUMIO_TOKEN_K8S_LOGS
              otlphttp/k8s_metrics:
                endpoint: https://${fqdn_ingest}/api/v1/ingest/otlp
                headers:
                  Authorization: Bearer $HUMIO_TOKEN_K8S_METRICS                    
            receivers:
              k8s_events:
              k8s_cluster:
                node_conditions_to_report:
                  [Ready, DiskPressure, MemoryPressure, PIDPressure, NetworkUnavailable]
                allocatable_types_to_report: [cpu, memory]              
              k8sobjects:
                auth_type: serviceAccount
                objects:
                  - name: pods
                    mode: pull
                    field_selector: status.phase=Running
                    interval: 15m
                  - name: events
                    mode: watch
                    group: events.k8s.io                
            processors:
              memory_limiter:
                check_interval: 1s
                limit_percentage: 75
                spike_limit_percentage: 15
              batch:
                send_batch_size: 1000
                timeout: 5s
            extensions:
              health_check:
                endpoint: 0.0.0.0:13133
              pprof:
                endpoint: :1888
              zpages:
                endpoint: :55679

            service:
              extensions: [pprof, zpages, health_check]
              pipelines:
                metrics:
                  receivers: [k8s_cluster]
                  processors: [batch]
                  exporters: [otlphttp/k8s_metrics]
                logs:
                  receivers: [k8s_events,k8sobjects,k8s_cluster]
                  processors: [batch]
                  exporters: [otlphttp/k8s_logs]
