apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: otel-node
  namespace: otel-system
spec:
  interval: 10m
  timeout: 5m
  chart:
    spec:
      chart: opentelemetry-collector
      version: "0.101.2"
      sourceRef:
        kind: HelmRepository
        name: otel
        namespace: flux-repos
      interval: 5m
  releaseName: otel-node
  targetNamespace: otel-system
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  test:
    enable: false
  dependsOn:
    - name: otel-operator
      namespace: flux-releases-region
  values:
    mode: daemonset

    image:
      repository: "otel/opentelemetry-collector-k8s"

    command:
      name: "otelcol-k8s"
    extraEnvs:
      - name: K8S_NODE_NAME
        valueFrom:
          fieldRef:
            fieldPath: spec.nodeName
      - name: HUMIO_TOKEN_K8S_LOGS
        valueFrom:
          secretKeyRef:
            name: infra-kubernetes-ingest-token
            key: token
      - name: HUMIO_TOKEN_K8S_METRICS
        valueFrom:
          secretKeyRef:
            name: metrics-kubernetes-ingest-token
            key: token
      - name: HUMIO_INGEST_HOST
        value: logscale-ingest.partition.ref.logsr.life
    serviceAccount:
      create: true
    clusterRole:
      create: true
    service:
      enabled: true
    presets:
      logsCollection:
        enabled: true
        includeCollectorLogs: true
        storeCheckpoints: true
      kubernetesAttributes:
        enabled: true
        extractAllPodLabels: true
    config:
      receivers:
        jaeger:
          protocols:
            grpc:
              endpoint: "[$${env:MY_POD_IP}]:14250"
            thrift_http:
              endpoint: "[$${env:MY_POD_IP}]:14268"
            thrift_compact:
              endpoint: "[$${env:MY_POD_IP}]:6831"
        otlp:
          protocols:
            grpc:
              endpoint: "[$${env:MY_POD_IP}]:4317"
            http:
              endpoint: "[$${env:MY_POD_IP}]:4318"
        prometheus:
          config:
            scrape_configs:
              - job_name: opentelemetry-collector
                scrape_interval: 10s
                static_configs:
                  - targets:
                      - "[$${env:MY_POD_IP}]:8888"
        zipkin:
          endpoint: "[$${env:MY_POD_IP}]:9411"
        filelog:
          exclude: []
          include:
            - /var/log/pods/*/*/*.log
          include_file_name: false
          include_file_path: true
          operators:
            - id: container-parser
              max_log_size: 102400
              type: container
          retry_on_failure:
            enabled: true
          start_at: end
      extensions:
        health_check:
          endpoint: "[$${env:MY_POD_IP}]:13133"
      processors:
        batch: {}
        k8sattributes:
          extract:
            metadata:
              - k8s.namespace.name
              - k8s.deployment.name
              - k8s.statefulset.name
              - k8s.daemonset.name
              - k8s.cronjob.name
              - k8s.job.name
              - k8s.node.name
              - k8s.pod.name
              - k8s.pod.uid
              - k8s.pod.start_time
              - container.image.name
              - container.image.tag
          passthrough: false
          pod_association:
            - sources:
                - from: resource_attribute
                  name: k8s.pod.ip
            - sources:
                - from: resource_attribute
                  name: k8s.pod.uid
            - sources:
                - from: connection
        memory_limiter:
          check_interval: 5s
          limit_percentage: 80
          spike_limit_percentage: 25
      exporters:
        otlphttp/k8s_logs:
          endpoint: https://logscale-ingest.partition.ref.logsr.life/api/v1/ingest/otlp
          headers:
            Authorization: Bearer $${env:HUMIO_TOKEN_K8S_LOGS}
        otlphttp/k8s_metrics:
          endpoint: https://logscale-ingest.partition.ref.logsr.life/api/v1/ingest/otlp
          headers:
            Authorization: Bearer $${env:HUMIO_TOKEN_K8S_METRICS}
      service:
        pipelines:
          logs:
            receivers:
              - filelog
            processors:
              - k8sattributes
              - batch
            exporters:
              - otlphttp/k8s_logs
        telemetry:
          logs:
            encoding: json
          metrics:
            address: "[$${env:MY_POD_IP}]:8888"
