apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: otel-node
  namespace: otel-system
spec:
  interval: 10m
  timeout: 5m
  chart:
    spec:
      chart: opentelemetry-collector
      version: "0.104.0"
      sourceRef:
        kind: HelmRepository
        name: otel
        namespace: flux-repos
      interval: 5m
  releaseName: otel-node
  targetNamespace: otel-system
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  test:
    enable: false
  driftDetection:
    mode: enabled
  values:
    mode: daemonset

    image:
      repository: "otel/opentelemetry-collector-k8s"

    command:
      name: "otelcol-k8s"
    extraEnvs:
      # - name: K8S_NODE_NAME
      #   valueFrom:
      #     fieldRef:
      #       fieldPath: spec.nodeName
      - name: HUMIO_TOKEN_K8S_LOGS
        valueFrom:
          secretKeyRef:
            name: infra-kubernetes-ingest-token
            key: token
      - name: HUMIO_TOKEN_K8S_METRICS
        valueFrom:
          secretKeyRef:
            name: metrics-kubernetes-ingest-token
            key: token
      - name: HUMIO_INGEST_HOST
        value: logscale-ingest.partition.ref.logsr.life
      - name: HOST_PROC
        value: /hostfs/proc
      - name: HOST_SYS
        value: /hostfs/sys
      - name: HOST_ETC
        value: /hostfs/etc
      - name: HOST_VAR
        value: /hostfs/var
      - name: HOST_RUN
        value: /hostfs/run
      - name: HOST_DEV
        value: /hostfs/dev
      - name: HOST_ROOT
        value: /hostfs
    serviceAccount:
      create: true
      annotations:
        eks.amazonaws.com/role-arn: arn:aws:iam::042445652404:role/otel-sa20240817134336470800000002
    clusterRole:
      create: true
    rollout:
      rollingUpdate:
        # When 'mode: daemonset', maxSurge cannot be used when hostPort is set for any of the ports
        # maxSurge: 25%
        maxUnavailable: 50%
    service:
      enabled: true
    presets:
      logsCollection:
        enabled: true
        includeCollectorLogs: true
        storeCheckpoints: true
      kubernetesAttributes:
        enabled: true
        extractAllPodLabels: true
      hostMetrics:
        enabled: true
    config:
      receivers:
        jaeger:
          protocols:
            grpc:
              endpoint: "[$${env:MY_POD_IP}]:14250"
            thrift_http:
              endpoint: "[$${env:MY_POD_IP}]:14268"
            thrift_compact:
              endpoint: "[$${env:MY_POD_IP}]:6831"
        otlp:
          protocols:
            grpc:
              endpoint: "[$${env:MY_POD_IP}]:4317"
            http:
              endpoint: "[$${env:MY_POD_IP}]:4318"
        prometheus:
          config:
            scrape_configs:
              - job_name: opentelemetry-collector
                scrape_interval: 10s
                static_configs:
                  - targets:
                      - "[$${env:MY_POD_IP}]:8888"
        zipkin:
          endpoint: "[$${env:MY_POD_IP}]:9411"
        filelog:
          exclude: []
          include:
            - /var/log/pods/*/*/*.log
          include_file_name: false
          include_file_path: true
          operators:
            - id: container-parser
              max_log_size: 102400
              type: container
          retry_on_failure:
            enabled: true
          start_at: end
      extensions:
        health_check:
          endpoint: "[$${env:MY_POD_IP}]:13133"
      processors:
        batch: {}
        k8sattributes:
          extract:
            metadata:
              - k8s.namespace.name
              - k8s.deployment.name
              - k8s.statefulset.name
              - k8s.daemonset.name
              - k8s.cronjob.name
              - k8s.job.name
              - k8s.node.name
              - k8s.pod.name
              - k8s.pod.uid
              - k8s.pod.start_time
              - container.image.name
              - container.image.tag
          passthrough: false
          pod_association:
            - sources:
                - from: resource_attribute
                  name: k8s.pod.ip
            - sources:
                - from: resource_attribute
                  name: k8s.pod.uid
            - sources:
                - from: connection
        resourcedetection/env:
          detectors: [env]
          timeout: 2s
          override: false
        resourcedetection/system:
          detectors: [system]
          timeout: 2s
          override: false
          system:
            hostname_sources: ["os"]
            resource_attributes:
              host.arch:
                enabled: true
              host.id:
                enabled: true
              host.name:
                enabled: false
              host.cpu.vendor.id:
                enabled: true
              host.cpu.family:
                enabled: true
              host.cpu.model.id:
                enabled: true
              host.cpu.model.name:
                enabled: true
              os.description:
                enabled: true
              os.type:
                enabled: true
        resourcedetection/cloud:
          detectors: [ec2]
          timeout: 15s
          override: false
          ec2:
            # A list of regex's to match tag keys to add as resource attributes can be specified
            tags:
              - ^.
            resource_attributes:
              host.name:
                enabled: true
              host.id:
                enabled: true
        resourcedetection/k8s:
          detectors: [k8snode, eks]
          timeout: 15s
          override: false
          eks:
            resource_attributes:
              k8s.cluster.name:
                enabled: true

        memory_limiter:
          check_interval: 5s
          limit_percentage: 80
          spike_limit_percentage: 25
      exporters:
        otlphttp/k8s_logs:
          endpoint: https://logscale-ingest.partition.ref.logsr.life/api/v1/ingest/otlp
          headers:
            Authorization: Bearer $${env:HUMIO_TOKEN_K8S_LOGS}
        otlphttp/k8s_metrics:
          endpoint: https://logscale-ingest.partition.ref.logsr.life/api/v1/ingest/otlp
          headers:
            Authorization: Bearer $${env:HUMIO_TOKEN_K8S_METRICS}
      service:
        pipelines:
          logs:
            receivers:
              - filelog
              - otlp
            processors:
              - resourcedetection/system
              - resourcedetection/env
              - resourcedetection/k8s
              - resourcedetection/cloud
              - k8sattributes
              - batch
            exporters:
              - otlphttp/k8s_logs
              - debug
          metrics:
            exporters:
              - otlphttp/k8s_metrics
            processors:
              - memory_limiter
              - batch
            receivers:
              - otlp
              - prometheus
              - hostmetrics
        telemetry:
          logs:
            encoding: json
          metrics:
            address: "[$${env:MY_POD_IP}]:8888"
