apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: cilium
  namespace: flux-system
spec:
  interval: 10m
  timeout: 5m
  chart:
    spec:
      chart: cilium
      version: "1.15.0-rc.1"
      sourceRef:
        kind: HelmRepository
        name: cilium
      interval: 5m
  releaseName: cilium
  targetNamespace: kube-system
  install:
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
  test:
    enable: false
  driftDetection:
    mode: enabled
  dependsOn:
    - name: prometheus-operator-crds
  values:
    cni:
      chainingMode: aws-cni
      exclusive: false
    routingMode: native
    enableIPv4Masquerade: false
    enableIPv6Masquerade: false
    endpointRoutes:
      enabled: true
    ipv6:
      enabled: true
    annotateK8sNode: true
    operator:
      podDisruptionBudget:
        enabled: true
    hubble:
      relay:
        enabled: true
      ui:
        enabled: true
