apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: descheduler
  namespace: flux-releases-region
spec:
  interval: 10m
  timeout: 5m
  chart:
    spec:
      chart: descheduler
      version: "0.32.1"
      sourceRef:
        kind: HelmRepository
        name: descheduler
        namespace: flux-repos
      interval: 5m
  releaseName: descheduler
  targetNamespace: kube-system
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  test:
    enable: false
  driftDetection:
    mode: enabled
    ignore:
      - paths: ["/spec/replicas"]
        target:
          kind: Deployment
  dependsOn:
    - name: karpenter-node-pools
  values:
    kind: Deployment

    deschedulerPolicy:
      ignorePvcPods: false
      evictLocalStoragePods: true
      evictSystemCriticalPods: true
      strategies:
        LowNodeUtilization:
          enabled: true
          params:
            nodeResourceUtilizationThresholds:
              thresholds:
                cpu: 20
                memory: 20
                pods: 20
              targetThresholds:
                cpu: 75
                memory: 75
                pods: 100
    # Specifies the replica count for Deployment
    # Set leaderElection if you want to use more than 1 replica
    # Set affinity.podAntiAffinity rule if you want to schedule onto a node
    # only if that node is in the same zone as at least one already-running descheduler
    replicas: 2

    # Specifies whether Leader Election resources should be created
    # Required when running as a Deployment
    # NOTE: Leader election can't be activated if DryRun enabled
    leaderElection:
      enabled: true
      leaseDuration: 15s
      renewDeadline: 10s
      retryPeriod: 2s
      resourceLock: "leases"
      resourceName: "descheduler"
      resourceNamescape: "kube-system"
    resources:
      requests:
        cpu: 500m
        memory: 256Mi
      limits:
        cpu: 2
        memory: 512Mi
    priorityClassName: "system-cluster-critical"

    affinity:
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
                - key: app.kubernetes.io/component
                  operator: In
                  values:
                    - descheduler
                - key: app.kubernetes.io/instance
                  operator: In
                  values:
                    - descheduler
            topologyKey: kubernetes.io/hostname
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: kubernetes.io/os
                  operator: In
                  values:
                    - linux
    topologySpreadConstraints:
      - maxSkew: 2
        minDomains: 2
        whenUnsatisfiable: DoNotSchedule
        topologyKey: topology.kubernetes.io/zone
        labelSelector:
          matchLabels:
            app.kubernetes.io/component: descheduler
            app.kubernetes.io/instance: descheduler
        matchLabelKeys:
          - pod-template-hash
