apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: grafana
  namespace: flux-releases-region
spec:
  interval: 10m
  timeout: 5m
  chart:
    spec:
      chart: grafana-operator
      version: "v5.17.0"
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-repos
      interval: 5m
  releaseName: grafana
  targetNamespace: grafana-operator
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  test:
    enable: false
  driftDetection:
    mode: enabled
    ignore:
      - paths: ["/spec/replicas"]
        target:
          kind: Deployment
  values:
    priorityClassName: partition-high
