apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: trust-manager
  namespace: cert-manager
spec:
  interval: 10m
  timeout: 5m
  chart:
    spec:
      chart: trust-manager
      version: "v0.13.0"
      sourceRef:
        kind: HelmRepository
        name: jetstack
        namespace: flux-repos
      interval: 5m
  releaseName: trust-manager
  targetNamespace: cert-manager
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  test:
    enable: false
  driftDetection:
    mode: disabled
    ignore:
      - paths: ["/spec/replicas"]
        target:
          kind: Deployment
  values:
    crds:
      enabled: true
    replicaCount: 2
    global:
      priorityClassName: "system-cluster-critical"
    podDisruptionBudget:
      enabled: true
    resources:
      requests:
        cpu: 15m
        memory: 105M
      limits:
        cpu: 1
        memory: 512M
    affinity:
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
                - key: app.kubernetes.io/component
                  operator: In
                  values:
                    - controller
                - key: app.kubernetes.io/instance
                  operator: In
                  values:
                    - trust-manager
            topologyKey: kubernetes.io/hostname
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: kubernetes.io/os
                  operator: In
                  values:
                    - linux
    topologySpreadConstraints:
      - maxSkew: 2
        minDomains: 2
        whenUnsatisfiable: DoNotSchedule
        topologyKey: topology.kubernetes.io/zone
        labelSelector:
          matchLabels:
            app.kubernetes.io/component: controller
            app.kubernetes.io/instance: trust-manager
        matchLabelKeys:
          - pod-template-hash
