apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: casdoor
  namespace: identity
spec:
  interval: 10m
  timeout: 5m
  chart:
    spec:
      chart: casdoor-helm-charts
      version: "0.4.5"
      sourceRef:
        kind: HelmRepository
        name: casdoor
      interval: 5m
  releaseName: casdoor
  targetNamespace: identity
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  test:
    enable: false
  driftDetection:
    mode: enabled
    ignore:
      - paths: ["/spec/replicas"]
        target:
          kind: Deployment
  dependsOn:
    - name: casdoor-db
  valuesFrom:
    - kind: Secret
      name: casdoor.identity-db.credentials.postgresql.acid.zalan.do
      valuesKey: password
      targetPath: global.dbpass
  values:
    ingress:
      enabled: true
      annotations:
        alb.ingress.kubernetes.io/group.name: global-internet
        alb.ingress.kubernetes.io/scheme: internet-facing
      tls:
        - hosts:
            - identity.ref.loglabs.net
      hosts:
        - host: identity.ref.loglabs.net
          paths:
            - path: /
              pathType: Prefix
      className: alb
    config: |
      appname = casdoor
      httpport = {{ .Values.service.port }}
      runmode = prod
      SessionOn = true
      copyrequestbody = true
      driverName = postgres
      dataSourceName = "user=casdoor password={{ .Values.global.dbpass }} host=identity-db port=5432 dbname=casdoor"
      dbName =
      redisEndpoint =
      defaultStorageProvider =
      isCloudIntranet = false
      authState = "casdoor"
      socks5Proxy = ""
      verificationCodeTimeout = 10
      initScore = 0
      logPostOnly = true
      origin =
      enableGzip = true
    affinity:
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
                - key: app.kubernetes.io/name
                  operator: In
                  values:
                    - casdoor-helm-charts
            topologyKey: kubernetes.io/hostname
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: kubernetes.io/os
                  operator: In
                  values:
                    - linux
                - key: kubernetes.io/arch
                  operator: In
                  values:
                    - amd64
        preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            preference:
              matchExpressions:
                - key: role
                  operator: NotIn
                  values:
                    - system


    topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: topology.kubernetes.io/zone
        whenUnsatisfiable: DoNotSchedule
        labelSelector:
          matchLabels:
            app.kubernetes.io/name: casdoor-helm-charts
        matchLabelKeys:
          - pod-template-hash
