apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: casdoor-redis
  namespace: identity
spec:
  interval: 10m
  timeout: 5m
  chart:
    spec:
      chart: redis-cluster
      version: "0.15.11"
      sourceRef:
        kind: HelmRepository
        name: ot-operators
        namespace: flux-system
      interval: 5m
  releaseName: identity-redis
  targetNamespace: identity
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  test:
    enable: false
  driftDetection:
    mode: warn
    ignore:
      - paths: ["/spec/replicas"]
        target:
          kind: Deployment
  dependsOn:
    - name: redis-operator
      namespace: flux-system
  values:
    redisCluster:
      clusterSize: 3
    redisLeader:
        affinity:
          podAntiAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              - labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - redis-cluster-leader
                        - redis-cluster-follower
                topologyKey: "kubernetes.io/hostname"
    redisFollower:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - redis-cluster-follower
                      - redis-cluster-leader
              topologyKey: "kubernetes.io/hostname"
    storage:
      volumeClaimTemplate:
        spec:
          # storageClassName: standard
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 1Gi
          storageClassName: gp3
      nodeConfVolumeClaimTemplate:
        spec:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 1Gi
          storageClassName: gp3