repos:
  - repo: "https://github.com/pre-commit/pre-commit-hooks"
    rev: "v4.4.0"
    hooks:
      - id: "trailing-whitespace"
      - id: "end-of-file-fixer"
      - id: "fix-byte-order-marker"
      - id: "mixed-line-ending"
      - id: "check-merge-conflict"
      - id: "check-case-conflict"
      - id: "check-json"
      - id: "pretty-format-json"
        args:
          - "--autofix"
          - "--no-sort-keys"
  # - repo: https://github.com/gruntwork-io/pre-commit
  #   rev: v0.1.23
  #   hooks:
  #     - id: terraform-fmt
  #       # args:
  #       #   - --args=-write=true
  #     - id: terraform-validate
  #     - id: tflint
  #     - id: shellcheck
  #     - id: gofmt
  #     - id: golint
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.77.1
    hooks:
      - id: terraform_fmt
        args:
          - --args=-diff
          - --args=-write=true
        stages: [pre-commit]
  #     - id: terraform_docs
  #       stages: [commit]
  #     - id: terraform_tflint
  #       files: \.tf$
