apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: logscale
spec:
  interval: 10m
  timeout: 5m
  chart:
    spec:
      chart: logscale
      version: "7.0.0-next.118"
      sourceRef:
        kind: HelmRepository
        name: logscale-contrib-ls
        namespace: flux-system
      interval: 5m
  releaseName: logscale
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  test:
    enable: false
  driftDetection:
    mode: warn
    ignore:
      - paths: ["/spec/replicas"]
        target:
          kind: Deployment
  # dependsOn:
  #   - name: kafka-topics
  valuesFrom:
    - kind: ConfigMap
      name: clustervars
      valuesKey: platformType
      targetPath: platform.provider
    - kind: ConfigMap
      name: clustervars
      valuesKey: platformType
      targetPath: humio.buckets.type
    - kind: ConfigMap
      name: clustervars
      valuesKey: aws_region
      targetPath: humio.buckets.region
    - kind: ConfigMap
      name: clustervars
      valuesKey: aws_region
      targetPath: humio.buckets.region
    - kind: ConfigMap
      name: logscalevars
      valuesKey: bucket_storage
      targetPath: humio.buckets.storage
    - kind: ConfigMap
      name: logscalevars
      valuesKey: bucket_prefix
      targetPath: humio.buckets.prefix
    - kind: ConfigMap
      name: logscalevars
      valuesKey: kafka_prefix
      targetPath: humio.kafka.topicPrefix
    - kind: ConfigMap
      name: logscalevars
      valuesKey: logscale_sa_name
      targetPath: humio.serviceAccount.name
    - kind: ConfigMap
      name: logscalevars
      valuesKey: logscale_sa_arn
      targetPath: humio.serviceAccount.annotations.eks\.amazonaws\.com/role-arn
    - kind: ConfigMap
      name: logscalevars
      valuesKey: logscale_license
      targetPath: humio.license

  values:
    fullnameOverride: logscale
    image:
      tag: 1.118.2
    humio:
      fqdn: logscale-ops.ref.loglabs.net
      fqdnInputs: logscale-ops-inputs.ref.loglabs.net
      kafka:
        manager: external
        prefixEnable: true
        bootstrap: kafka-kafka-bootstrap:9092

      auth:
        rootUser: ryan.faircloth@crowdstrike.com
        method: saml
        saml:
          signOnUrl: https://test.qa.logsr.life
          entityID: https://test.qa.logsr.life
          idpCertificate: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM4RENDQWRpZ0F3SUJBZ0lRTldqZE10UmZqYTlHdEFxVmVvcW1vakFOQmdrcWhraUc5dzBCQVFzRkFEQTBNVEl3TUFZRFZRUUQKRXlsTmFXTnliM052Wm5RZ1FYcDFjbVVnUm1Wa1pYSmhkR1ZrSUZOVFR5QkRaWEowYVdacFkyRjBaVEFlRncweU16QXhNVGt3TVRNegpNVFphRncweU5qQXhNVGt3TVRNek1UWmFNRFF4TWpBd0JnTlZCQU1US1UxcFkzSnZjMjltZENCQmVuVnlaU0JHWldSbGNtRjBaV1FnClUxTlBJRU5sY25ScFptbGpZWFJsTUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUEzaENrcTdLMGM4dUQKbG1vYnEwS0JmcDZlUVNUajR0REgrRDhPbWxBUllzdG1aQWpnRDNxUnBEaHBwbC9PSWRFZzNPVHhzTEZqaG9yS3l0ek5Kc2pWcExWeQpCYnZ4Qm1KUnBETFd1TTNlMDlpcWltYTI2QkR4L3cybEJYd2kvMExXcVpVQitBNlhydmE0QVk0Qmp0Y1loZEg3Y09LdURPeFhROVQzCjl6QXQyQTgyRzRSWHRIY1JwaEZoMnN1RCt6anpLYU1ldVVGU0l0T0xLS0Q4eXo0TEI5YjExNys5bWdMQytmNTJzaktQUTVUVGlFcHAKWDhZWWpQR0RTSEhTbE8vdWt6aEVvR2xmUktmSlhsZE9HcjR3ZHlERVRlR3ZVWkhyS1l6eFN1djI4UUhEUnhjSkZWeEhFWTQxOGxhbgpEc3ZrbUlxM0FYU1d3TmNGTHpMUlUvVkRUUUlEQVFBQk1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQVAzTk8rT2h1dWY0VldpR3BvCmVwSE9yRDNKMG91ZVdhOWlyTDhtOW9XWXBhQnl4ZTlJZzYrTFVrcCtnYnUxZ2FReE55QllQZDVLRGVQMmRvRG5zVmhFMGg4VXNiNlUKMXlYQVl0WTFQTU1ucm45a2lSVG5NMU9zMWp3R0h4NHJBNzdXYXpQYU5SczBSaUg5aTBFcnRmSUdwNFpqU0N3MHNLR2xZRFArTXNBZgpIaklGTW0zSGtQMUVvYWwzbkdrT0VYaEhSYWJwOTNiOExOU291T0VhZCtJaElXaUdCalczU0puVyt5TVVQWFBWQlBhK2ZabWNiZzMxCkNNSTM5eGRvSUlVRVY2N3Zkb3cvdU5ad1IybWhkbUZkWHNpUDNSR3NkTDRZRi9XRFFxQWtsdUU5SmlseGJhSzA4aWNQc0tOV1pPblMKdWwybEdEZWpLMnZIT05saU5vNXQKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=

      nodeCount: 3
      #In general for these node requests and limits should match
      resources:
        requests:
          memory: 24Gi
          cpu: 2
        limits:
          memory: 24Gi
          cpu: 2
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: "kubernetes.io/arch"
                    operator: "In"
                    values: ["amd64"]
                  - key: "kubernetes.io/os"
                    operator: "In"
                    values: ["linux"]
                  - key: "karpenter.k8s.aws/instance-local-nvme"
                    operator: Gt
                    values:
                      - "910"
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: humio.com/node-pool
                    operator: In
                    values: 
                    - "logscale"
                    - "logscale-ingest-only"
                    - "logscale-http-only"
                  - key: app.kubernetes.io/name
                    operator: In
                    values: 
                    - "zookeeper"
                    - "kafka"
              topologyKey: "kubernetes.io/hostname"
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: topology.kubernetes.io/zone
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchExpressions:
              - key: humio.com/node-pool
                operator: In
                values:
                  - logscale
      tolerations:
        - key: topolvm.io/local
          operator: "Equal"
          value: "true"
      dataVolumePersistentVolumeClaimSpecTemplate:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: "900Gi"
        # storageClassName: "gp3"
        storageClassName: "nvme-xfs"
      frontEndDataVolumePersistentVolumeClaimSpecTemplate:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: "10Gi"
        storageClassName: "gp3"
      priorityClass: partition-high

      ingress:
        ui:
          className: alb-partition
          enabled: true
          tls: true
          annotations:
            alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS":443}]'
            alb.ingress.kubernetes.io/ssl-redirect: '443'      
        inputs:
          className: alb-partition
          enabled: true
          tls: true
          annotations:
            alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS":443}]'
            alb.ingress.kubernetes.io/ssl-redirect: '443'      

      nodepools:
        ingest:
          priorityClass: partition-medium
          nodeCount: 3
          resources:
            limits:
              cpu: "2"
              memory: 3Gi
            requests:
              cpu: "2"
              memory: 3Gi
          affinity:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                  - matchExpressions:
                      - key: "kubernetes.io/arch"
                        operator: "In"
                        values: ["amd64"]
                      - key: "kubernetes.io/os"
                        operator: "In"
                        values: ["linux"]
            podAntiAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                - labelSelector:
                    matchExpressions:
                      - key: humio.com/node-pool
                        operator: In
                        values: 
                        - "logscale"
                        - "logscale-ingest-only"
                        - "logscale-http-only"
                  topologyKey: "kubernetes.io/hostname"
          topologySpreadConstraints:
            - maxSkew: 1
              topologyKey: topology.kubernetes.io/zone
              whenUnsatisfiable: DoNotSchedule
              labelSelector:
                matchExpressions:
                  - key: humio.com/node-pool
                    operator: In
                    values:
                      - logscale-ingest-only
        ui:
          priorityClass: partition-low
          nodeCount: 3
          resources:
            limits:
              cpu: "2"
              memory: 3Gi
            requests:
              cpu: "2"
              memory: 3Gi
          affinity:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                  - matchExpressions:
                      - key: "kubernetes.io/arch"
                        operator: "In"
                        values: ["amd64"]
                      - key: "kubernetes.io/os"
                        operator: "In"
                        values: ["linux"]
            podAntiAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                - labelSelector:
                    matchExpressions:
                      - key: humio.com/node-pool
                        operator: In
                        values: 
                        - "logscale"
                        - "logscale-ingest-only"
                        - "logscale-http-only"
                  topologyKey: "kubernetes.io/hostname"
          topologySpreadConstraints:
            - maxSkew: 1
              topologyKey: topology.kubernetes.io/zone
              whenUnsatisfiable: DoNotSchedule
              labelSelector:
                matchExpressions:
                  - key: humio.com/node-pool
                    operator: In
                    values:
                      - "logscale-http-only"
