apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: casdoor-db
  namespace: identity
spec:
  interval: 10m
  timeout: 5m
  chart:
    spec:
      chart: raw
      version: "2.0.0"
      sourceRef:
        kind: HelmRepository
        name: bedag
      interval: 5m
  releaseName: identity-db
  targetNamespace: identity
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  test:
    enable: false
  driftDetection:
    mode: warn
    ignore:
      - paths: ["/spec/replicas"]
        target:
          kind: Deployment
  dependsOn:
    - name: flux-system/zalando
  values:
    - resources:
      kind: "postgresql"
      apiVersion: "acid.zalan.do/v1"
      metadata:
        name: "identity-db"
        labels:
          team: acid
      spec:
        teamId: "acid"
        postgresql:
          version: "15"
        numberOfInstances: 1
        volume:
          size: "10Gi"
        users:
          casdoor: []
        databases:
          casdoor: casdoor

        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: "2"
            memory: 1Gi
    -
