# apiVersion: helm.toolkit.fluxcd.io/v2beta2
# kind: HelmRelease
# metadata:
#   name: authentik-redis-sentinel
#   namespace: identity
# spec:
#   interval: 10m
#   timeout: 5m
#   chart:
#     spec:
#       chart: redis-sentinel
#       version: "0.15.11"
#       sourceRef:
#         kind: HelmRepository
#         name: ot-operators
#         namespace: flux-system
#       interval: 5m
#   releaseName: identity-redis-sentinel
#   targetNamespace: identity
#   install:
#     createNamespace: true
#     remediation:
#       retries: 3
#   upgrade:
#     remediation:
#       retries: 3
#   test:
#     enable: false
#   driftDetection:
#     mode: warn
#     ignore:
#       - paths: ["/spec/replicas"]
#         target:
#           kind: Deployment
#   dependsOn:
#     - name: redis-operator
#       namespace: flux-system
#     - name: authentik-redis
#   values:
#     redisSentinelConfig:
#       clusterSize: 3
#       resources:
#         requests:
#           cpu: 101m
#           memory: 128Mi
#       masterGroupName: identity
#       redisReplicationName: identity-redis
#     affinity:
#       podAntiAffinity:
#         requiredDuringSchedulingIgnoredDuringExecution:
#           - labelSelector:
#               matchExpressions:
#                 - key: app
#                   operator: In
#                   values:
#                     - redis-sentinel
#             topologyKey: "kubernetes.io/hostname"
  