# apiVersion: helm.toolkit.fluxcd.io/v2beta2
# kind: HelmRelease
# metadata:
#   name: authentik-redis
#   namespace: flux-releases-partition
# spec:
#   interval: 10m
#   timeout: 5m
#   chart:
#     spec:
#       chart: redis-replication
#       version: "0.15.11"
#       sourceRef:
#         kind: HelmRepository
#         name: ot-operators
#         namespace: flux-releases-region
#       interval: 5m
#   releaseName: identity-redis
#   targetNamespace: identity
#   install:
#     remediation:
#       retries: 3
#   upgrade:
#     remediation:
#       retries: 3
#   test:
#     enable: false
#   driftDetection:
#     mode: warn
#     ignore:
#       - paths: ["/spec/replicas"]
#         target:
#           kind: Deployment
#   dependsOn:
#     - name: redis-operator
#       namespace: flux-releases-region
#   values:
#     redisReplication:
#       clusterSize: 3
#       resources:
#         requests:
#           cpu: 101m
#           memory: 128Mi

#     affinity:
#         podAntiAffinity:
#           requiredDuringSchedulingIgnoredDuringExecution:
#             - labelSelector:
#                 matchExpressions:
#                   - key: app
#                     operator: In
#                     values:
#                       - redis-replication
#               topologyKey: "kubernetes.io/hostname"
#     storage:
#       volumeClaimTemplate:
#         spec:
#           storageClassName: gp3
#           accessModes: ["ReadWriteOnce"]
#           resources:
#             requests:
#               storage: 10Gi
