apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: authentik-db
  namespace: identity
spec:
  interval: 10m
  timeout: 5m
  chart:
    spec:
      chart: raw
      version: "2.0.0"
      sourceRef:
        kind: HelmRepository
        name: bedag
        namespace: flux-repos
      interval: 5m
  releaseName: authentik-db
  targetNamespace: identity
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  test:
    enable: false
  driftDetection:
    mode: warn
    ignore:
      - paths: ["/spec/replicas"]
        target:
          kind: Deployment
  dependsOn:
    - name: zalando
      namespace: flux-releases-region
  values:
    resources:
      - kind: "postgresql"
        apiVersion: "acid.zalan.do/v1"
        metadata:
          name: "identity-db"
          labels:
            team: acid
        spec:
          teamId: "acid"
          postgresql:
            version: "15"
          numberOfInstances: 3
          volume:
            size: "20Gi"
          users:
            authentik: []
          databases:
            authentik: authentik

          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: "2"
              memory: 1Gi
