apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: zalando-pg-ui
  namespace: flux-repos
spec:
  interval: 60m
  url: https://opensource.zalando.com/postgres-operator/charts/postgres-operator-ui
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: zalando-pg
  namespace: flux-repos
spec:
  interval: 60m
  url: https://opensource.zalando.com/postgres-operator/charts/postgres-operator
