apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: aws-load-balancer-classes
  namespace: flux-system
spec:
  interval: 10m
  timeout: 5m
  chart:
    spec:
      chart: raw
      version: "2.0.0"
      sourceRef:
        kind: HelmRepository
        name: bedag
      interval: 5m
  releaseName: aws-load-balancer-classes
  targetNamespace: kube-system
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  test:
    enable: false
  driftDetection:
    mode: warn
    ignore:
      - paths: ["/spec/replicas"]
        target:
          kind: Deployment
  dependsOn:
    - name: aws-load-balancer-controller
  valuesFrom:
    - kind: ConfigMap
      name: clustervars
      valuesKey: aws_s3_log_bucket
      targetPath: settings.logbucket
    - kind: ConfigMap
      name: clustervars
      valuesKey: aws_eks_cluster_name
      targetPath: settings.clusterName
  values:
    templates:
      - |
        apiVersion: networking.k8s.io/v1
        kind: IngressClass
        metadata:
          name: alb-partition
        spec:
          controller: ingress.k8s.aws/alb
          parameters:
            apiGroup: elbv2.k8s.aws
            kind: IngressClassParams
            name: alb-partition
      - |
        apiVersion: elbv2.k8s.aws/v1beta1
        kind: IngressClassParams
        metadata:
          name: alb-partition
        spec:
          scheme: internet-facing
          ipAddressType: dualstack
          group: global-internet
          loadBalancerAttributes:
            - key: access_logs.s3.enabled
              value: true
            - key: access_logs.s3.bucket
              value: {{ .Values.settings.logbucket }}
