apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: karpenter-nodes
  namespace: flux-system
spec:
  interval: 10m
  timeout: 5m
  chart:
    spec:
      chart: raw
      version: "2.0.0"
      sourceRef:
        kind: HelmRepository
        name: bedag
      interval: 5m
  releaseName: karpenter-nodes
  targetNamespace: karpenter
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  test:
    enable: false
  driftDetection:
    mode: warn
    ignore:
      - paths: ["/spec/replicas"]
        target:
          kind: Deployment
  dependsOn:
    - name: karpenter
  valuesFrom:
    - kind: ConfigMap
      name: clustervars
      valuesKey: aws_eks_cluster_name
      targetPath: settings.clusterName
    - kind: ConfigMap
      name: clustervars
      valuesKey: aws_eks_endpoint
      targetPath: settings.clusterEndpoint
    - kind: ConfigMap
      name: clustervars
      valuesKey: aws_eks_sqsinterruptionQueueName
      targetPath: settings.interruptionQueueName
    - kind: ConfigMap
      name: clustervars
      valuesKey: aws_arn_karpenter
      targetPath: settings.roleArn
  values:
    templates:
      - |
        apiVersion: karpenter.k8s.aws/v1beta1
        kind: EC2NodeClass
        metadata:
          name: bottle
        spec:
          amiFamily: Bottlerocket
          role: \{\{ .Values.settings.roleArn }}
          subnetSelectorTerms:
          - tags:
              karpenter.sh/discovery: \{\{ .Values.settings.clusterName }}
          securityGroupSelectorTerms:
          - tags:
              karpenter.sh/discovery: \{\{ .Values.settings.clusterName }}
          tags:
            karpenter.sh/discovery: \{\{ .Values.settings.clusterName }}
