apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: zalando-ui
  namespace: flux-system
spec:
  interval: 10m
  timeout: 5m
  chart:
    spec:
      chart: "postgres-operator-ui"
      version: "1.10.1"
      sourceRef:
        kind: HelmRepository
        name: zalando-pg-ui
      interval: 5m
  dependsOn:
    - name: zalando
  releaseName: zalando-ui
  targetNamespace: postgres-operator
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  test:
    enable: false
  driftDetection:
    mode: enabled
    ignore:
      - paths: ["/spec/replicas"]
        target:
          kind: Deployment
