apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: kafka
  namespace: ${namespace}
spec:
  interval: 10m
  timeout: 5m
  chart:
    spec:
      chart: kafka-strimzi-cluster
      version: "4.3.9"
      sourceRef:
        kind: HelmRepository
        name: logscale-contrib
        namespace: flux-repos
      interval: 5m
  releaseName: kafka
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  test:
    enable: false
  values:
    fullnameOverride: ${kafka_name}
    metadataMode: enabled
    nodePools:
      enabled: true
      kafka:
        replicas: 4
        resources:
          # We usually recommend not to specify default resources and to leave this as a conscious
          # choice for the user. This also increases chances charts run on environments with little
          # resources, such as Minikube. If you do want to specify resources, uncomment the following
          # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
          limits:
            cpu: 1
            memory: 2000Mi
          requests:
            cpu: 100m
            memory: 1500Mi
        template:
          pod:
            affinity:
              podAntiAffinity:
                requiredDuringSchedulingIgnoredDuringExecution:
                  - labelSelector:
                      matchExpressions:
                        - key: strimzi.io/pool-name
                          operator: In
                          values:
                            - kafka
                    topologyKey: kubernetes.io/hostname
              nodeAffinity:
                requiredDuringSchedulingIgnoredDuringExecution:
                  nodeSelectorTerms:
                    - matchExpressions:
                        - key: kubernetes.io/os
                          operator: In
                          values:
                            - linux

            topologySpreadConstraints:
              - maxSkew: 2
                whenUnsatisfiable: ScheduleAnyway
                topologyKey: topology.kubernetes.io/zone
                labelSelector:
                  matchLabels:
                    strimzi.io/pool-name: kafka
                matchLabelKeys:
                  - pod-template-hash

        storage:
          type: persistent-claim
          size: 1500Gi
          deleteClaim: true
          # Must be SSD or NVME like storage IOPs is the primary node constraint
          class: cluster-block-base-ext4

      controller:
        enabled: true
        resources:
          # We usually recommend not to specify default resources and to leave this as a conscious
          # choice for the user. This also increases chances charts run on environments with little
          # resources, such as Minikube. If you do want to specify resources, uncomment the following
          # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
          limits:
            cpu: 1
            memory: 8Gi
          requests:
            cpu: 100m
            memory: 4Gi
        storage:
          type: persistent-claim
          size: 64Gi
          deleteClaim: true
          # Must be SSD or NVME like storage IOPs is the primary node constraint
          class: cluster-block-base-ext4
        template:
          pod:
            affinity:
              podAntiAffinity:
                requiredDuringSchedulingIgnoredDuringExecution:
                  - labelSelector:
                      matchExpressions:
                        - key: strimzi.io/pool-name
                          operator: In
                          values:
                            - controller
                    topologyKey: kubernetes.io/hostname
              nodeAffinity:
                requiredDuringSchedulingIgnoredDuringExecution:
                  nodeSelectorTerms:
                    - matchExpressions:
                        - key: kubernetes.io/os
                          operator: In
                          values:
                            - linux

            topologySpreadConstraints:
              - maxSkew: 2
                whenUnsatisfiable: ScheduleAnyway
                topologyKey: topology.kubernetes.io/zone
                labelSelector:
                  matchLabels:
                    strimzi.io/pool-name: controller
                matchLabelKeys:
                  - pod-template-hash
    cruiseControl:
      resources:
        # We usually recommend not to specify default resources and to leave this as a conscious
        # choice for the user. This also increases chances charts run on environments with little
        # resources, such as Minikube. If you do want to specify resources, uncomment the following
        # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
        limits:
          cpu: 4
          memory: 2Gi
        requests:
          cpu: 100m
          memory: 512Mi

      autoscaling:
        enabled: false
        minReplicas: 1
        maxReplicas: 100
        targetCPUUtilizationPercentage: 80
        # targetMemoryUtilizationPercentage: 80

      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/os
                    operator: In
                    values:
                      - linux

    topicOperator:
      resources:
        # We usually recommend not to specify default resources and to leave this as a conscious
        # choice for the user. This also increases chances charts run on environments with little
        # resources, such as Minikube. If you do want to specify resources, uncomment the following
        # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
        limits:
          cpu: 300m
          memory: 256Mi
        requests:
          cpu: 100m
          memory: 128Mi

      autoscaling:
        enabled: false
        minReplicas: 1
        maxReplicas: 100
        targetCPUUtilizationPercentage: 80
        # targetMemoryUtilizationPercentage: 80

    userOperator:
      resources:
        # We usually recommend not to specify default resources and to leave this as a conscious
        # choice for the user. This also increases chances charts run on environments with little
        # resources, such as Minikube. If you do want to specify resources, uncomment the following
        # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
        limits:
          cpu: 300m
          memory: 256Mi
        requests:
          cpu: 100m
          memory: 128Mi

      autoscaling:
        enabled: false
        minReplicas: 1
        maxReplicas: 100
        targetCPUUtilizationPercentage: 80
        # targetMemoryUtilizationPercentage: 80

    kafka:
      authorization:
        enabled: true
      listeners:
        internal:
          tls:
            authentication:
              enabled: true
              type: scram-sha-512
            certManager:
              enabled: true
              issuerRef:
                name: cluster-ca-issuer
            # secretName: kafka-tls

      autoscaling:
        enabled: false
        minReplicas: 1
        maxReplicas: 100
        targetCPUUtilizationPercentage: 80
        # targetMemoryUtilizationPercentage: 80

    zookeeper:
      replicas: 3
      resources:
        # We usually recommend not to specify default resources and to leave this as a conscious
        # choice for the user. This also increases chances charts run on environments with little
        # resources, such as Minikube. If you do want to specify resources, uncomment the following
        # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
        limits:
          cpu: 1
          memory: 2000Mi
        requests:
          cpu: 500m
          memory: 1500Mi
      storage:
        type: persistent-claim
        size: 5Gi
        deleteClaim: true
        # Must be SSD or NVME like storage IOPs is the  mary node constraint
        class: cluster-block-base-ext4

      autoscaling:
        enabled: false
        minReplicas: 1
        maxReplicas: 100
        targetCPUUtilizationPercentage: 80
        # targetMemoryUtilizationPercentage: 80

      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app.kubernetes.io/name
                    operator: In
                    values:
                      - zookeeper
              topologyKey: kubernetes.io/hostname
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/os
                    operator: In
                    values:
                      - linux

      topologySpreadConstraints:
        - maxSkew: 2
          whenUnsatisfiable: ScheduleAnyway
          topologyKey: topology.kubernetes.io/zone
          labelSelector:
            matchLabels:
              app.kubernetes.io/name: zookeeper
          matchLabelKeys:
            - pod-template-hash
