apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: otel
  namespace: otel-system
spec:
  interval: 10m
  timeout: 5m
  chart:
    spec:
      chart: otel-logscale
      version: "2.0.0"
      sourceRef:
        kind: HelmRepository
        name: logscalecontrib-otel
      interval: 5m
  releaseName: node
  targetNamespace: otel-system
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  test:
    enable: false
  driftDetection:
    mode: enabled
  valuesFrom:
    - kind: ConfigMap
      name: otel-values
