apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: karpenter-node-classes
  namespace: flux-system
spec:
  interval: 10m
  timeout: 5m
  chart:
    spec:
      chart: raw
      version: "2.0.0"
      sourceRef:
        kind: HelmRepository
        name: bedag
      interval: 5m
  releaseName: karpenter-node-classes
  targetNamespace: karpenter
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  test:
    enable: false
  dependsOn:
    - name: karpenter
  values:
    templates:
      - |
        apiVersion: karpenter.k8s.aws/v1beta1
        kind: EC2NodeClass
        metadata:
          name: al2
        spec:
          amiFamily: AL2
          role: ${node_iam_role_name}
          subnetSelectorTerms: ${jsonencode(subnet_selector)}
          securityGroupSelectorTerms:
          - id: ${node_security_group_id}
          tags:
            karpenter.sh/discovery: ${cluster_name}
      - |
        apiVersion: karpenter.k8s.aws/v1beta1
        kind: EC2NodeClass
        metadata:
          name: al2-storage
        spec:
          amiFamily: AL2
          role: ${node_iam_role_name}
          subnetSelectorTerms: ${jsonencode(subnet_selector)}
          securityGroupSelectorTerms:
          - id: ${node_security_group_id}
          tags:
            karpenter.sh/discovery: ${cluster_name}
          userData: |
              yum install nvme-cli -y
