apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: karpenter
  namespace: flux-system
spec:
  interval: 10m
  timeout: 5m
  chart:
    spec:
      chart: karpenter
      version: "v0.33.1"
      sourceRef:
        kind: HelmRepository
        name: karpenter
      interval: 5m
  releaseName: karpenter
  targetNamespace: karpenter
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  test:
    enable: false
  driftDetection:
    mode: enabled
    ignore:
      - paths: ["/spec/replicas"]
        target:
          kind: Deployment
  values:
    replicas: 2
    settings:
      clusterName: ${cluster_name}
      clusterEndpoint: ${cluster_endpoint}
      interruptionQueueName: ${queue_name}
      aws:
        enablePodENU: true
    serviceAccount:
      annotations:
        eks.amazonaws.com/role-arn: ${irsa_arn}
    controller:
      resources:
        requests:
          cpu: 1
          memory: 256Mi
        limits:
          cpu: 1
          memory: 256Mi
    podDisruptionBudget:
      enabled: true
    affinity:
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
                - key: app.kubernetes.io/component
                  operator: In
                  values:
                    - karpenter
                - key: app.kubernetes.io/instance
                  operator: In
                  values:
                    - karpenter
            topologyKey: kubernetes.io/hostname
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: kubernetes.io/os
                  operator: In
                  values:
                    - linux
        preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            preference:
              matchExpressions:
                - key: role
                  operator: NotIn
                  values:
                    - system
          - weight: 100
            preference:
              matchExpressions:
                - key: kubernetes.io/arch
                  operator: In
                  values:
                    - arm64

    topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: topology.kubernetes.io/zone
        whenUnsatisfiable: DoNotSchedule
        labelSelector:
          matchLabels:
            app.kubernetes.io/component: karpenter
            app.kubernetes.io/instance: karpenter
        matchLabelKeys:
          - pod-template-hash
    priorityClassName: "system-cluster-critical"
