apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: otel-operator
  namespace: flux-system
spec:
  interval: 10m
  timeout: 5m
  chart:
    spec:
      chart: "opentelemetry-operator"
      version: "0.47.0"
      sourceRef:
        kind: HelmRepository
        name: otel
      interval: 5m
  releaseName: otel-operator
  targetNamespace: otel-operator
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  test:
    enable: false
  driftDetection:
    mode: warn
    ignore:
      - paths: ["/spec/replicas"]
        target:
          kind: Deployment
  values:
    replicaCount: 2
    manager:
      resources:
        requests:
          cpu: 10m
          memory: 40Mi
    kubeRBACProxy:
      resources:
        requests:
          cpu: 10m
          memory: 40Mi
    watchAnyNamespace: true
    affinity:
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
                - key: app.kubernetes.io/name
                  operator: In
                  values:
                    - opentelemetry-operator
            topologyKey: kubernetes.io/hostname
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: kubernetes.io/os
                  operator: In
                  values:
                    - linux
        preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            preference:
              matchExpressions:
                - key: kubernetes.io/arch
                  operator: In
                  values:
                    - arm64

          - weight: 10
            preference:
              matchExpressions:
                - key: storageClass
                  operator: In
                  values:
                    - network
    topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: topology.kubernetes.io/zone
        whenUnsatisfiable: DoNotSchedule
        labelSelector:
          matchLabels:
            app.kubernetes.io/name: opentelemetry-operator
        matchLabelKeys:
          - pod-template-hash
