apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: strimzi
  namespace: flux-releases-region
spec:
  interval: 10m
  timeout: 5m
  chart:
    spec:
      chart: strimzi-kafka-operator
      version: "0.41.0"
      sourceRef:
        kind: HelmRepository
        name: strimzi
        namespace: flux-repos
      interval: 5m
  releaseName: strimzi-operator
  targetNamespace: strimzi-operator
  install:
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
  test:
    enable: false
  driftDetection:
    mode: enabled
    ignore:
      - paths: ["/spec/replicas"]
        target:
          kind: Deployment
  values:
    watchAnyNamespace: true
    replicas: 2
    resources:
      requests:
        cpu: "1"
        memory: 256Mi
      limits:
        cpu: "2"
        memory: 364Mi
    affinity:
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
                - key: name
                  operator: In
                  values:
                    - strimzi-cluster-operator
            topologyKey: kubernetes.io/hostname
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: kubernetes.io/os
                  operator: In
                  values:
                    - linux

    topologySpreadConstraints:
      - maxSkew: 2
        minDomains: 2
        whenUnsatisfiable: DoNotSchedule
        topologyKey: topology.kubernetes.io/zone
        labelSelector:
          matchLabels:
            name: strimzi-cluster-operator
        matchLabelKeys:
          - pod-template-hash
