apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: strimzi-drain-cleaner
  namespace: flux-system
spec:
  interval: 10m
  timeout: 5m
  chart:
    spec:
      chart: strimzi-drain-cleaner
      version: "1.0.1"
      sourceRef:
        kind: HelmRepository
        name: strimzi
      interval: 5m
  releaseName: strimzi-drain-cleaner
  targetNamespace: strimzi-drain-cleaner
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  test:
    enable: false
  driftDetection:
    mode: enabled
    ignore:
      - paths: ["/spec/replicas"]
        target:
          kind: Deployment
  dependsOn:
    - name: strimzi
    - name: cert-manager
  values:
    watchAnyNamespace: true
    replicas: 2
    affinity:
      resources:
        requests:
          cpu: 100m
          memory: 64Gi
        limits:
          cpu: 1
          memory: 128Gi
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
                - key: name
                  operator: In
                  values:
                    - strimzi-cluster-operator
            topologyKey: kubernetes.io/hostname
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: kubernetes.io/os
                  operator: In
                  values:
                    - linux
        preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            preference:
              matchExpressions:
                - key: kubernetes.io/arch
                  operator: In
                  values:
                    - arm64

          - weight: 10
            preference:
              matchExpressions:
                - key: storageClass
                  operator: In
                  values:
                    - network
    topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: topology.kubernetes.io/zone
        whenUnsatisfiable: DoNotSchedule
        labelSelector:
          matchLabels:
            name: strimzi-cluster-operator
        matchLabelKeys:
          - pod-template-hash
