apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: reflector
  namespace: region-flux-releases
spec:
  interval: 10m
  timeout: 5m
  chart:
    spec:
      chart: reflector
      version: "7.1.262"
      sourceRef:
        kind: HelmRepository
        name: emberstack
        namespace: flux-system
      interval: 5m
  releaseName: reflector
  targetNamespace: reflector-system
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  test:
    enable: false
  driftDetection:
    mode: enabled
    ignore:
      - paths: ["/spec/replicas"]
        target:
          kind: Deployment
  dependsOn:
    - name: prometheus-operator-crds
  values:
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: kubernetes.io/os
                  operator: In
                  values:
                    - linux
