apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: logscale-content-k8s
  namespace: ${namespace}
spec:
  interval: 10m
  timeout: 5m
  chart:
    spec:
      chart: raw
      version: "2.0.0"
      sourceRef:
        kind: HelmRepository
        name: bedag
        namespace: flux-repos
      interval: 5m
  releaseName: logscale-content-k8s
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  test:
    enable: false
  driftDetection:
    mode: warn
    ignore:
      - paths: ["/spec/replicas"]
        target:
          kind: Deployment
  dependsOn:
    - name: logscale
  values:
    templates:
      - |
        apiVersion: core.humio.com/v1alpha1
        kind: HumioRepository
        metadata:
          name: infra-kubernetes
        spec:
          managedClusterName: ${cluster_name}
          name: "infra-kubernetes"
          description: "Kubernetes infrastructure logs"
          allowDataDeletion: ${allowDataDeletion}
          retention:
            timeInDays: 30
      - |
        apiVersion: core.humio.com/v1alpha1
        kind: HumioRepository
        metadata:
          name: apps-kubernetes
        spec:
          managedClusterName: ${cluster_name}
          name: "apps-kubernetes"
          description: "Kubernetes apps logs"
          allowDataDeletion: ${allowDataDeletion}
          retention:
            timeInDays: 30
      - |
        apiVersion: core.humio.com/v1alpha1
        kind: HumioRepository
        metadata:
          name: metrics-kubernetes
        spec:
          managedClusterName: ${cluster_name}
          name: "metrics-kubernetes"
          description: "Kubernetes metrics"
          allowDataDeletion: ${allowDataDeletion}
          retention:
            timeInDays: 30
