createAggregateRoles: true
global:
  logging:
    format: json
  priorityClassName: "system-cluster-critical"
  affinity:
    podAntiAffinity: hard

    nodeAffinity:
      matchExpressions:
        - key: kubernetes.io/os
          operator: In
          values:
            - linux
  topologySpreadConstraints:
    - maxSkew: 1
      topologyKey: topology.kubernetes.io/zone
      whenUnsatisfiable: DoNotSchedule

redis-ha:
  enabled: true

controller:
  replicas: 1

server:
  pdb:
    enabled: true

  autoscaling:
    enabled: true
    minReplicas: 2

repoServer:
  pdb:
    enabled: true
  autoscaling:
    enabled: true
    minReplicas: 2

applicationSet:
  pdb:
    enabled: true
  replicas: 2
