installVPA: true
controller:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: kubernetes.io/os
                operator: In
                values:
                  - linux
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          preference:
            matchExpressions:
              - key: kubernetes.io/arch
                operator: In
                values:
                  - arm64
        - weight: 50
          preference:
            matchExpressions:
              - key: computeClass
                operator: In
                values:
                  - general
        - weight: 10
          preference:
            matchExpressions:
              - key: storageClass
                operator: In
                values:
                  - network
dashboard:
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
              - key: app.kubernetes.io/component
                operator: In
                values:
                  - dashboard
              - key: app.kubernetes.io/instance
                operator: In
                values:
                  - goldilocks
          topologyKey: kubernetes.io/hostname
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: kubernetes.io/os
                operator: In
                values:
                  - linux
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          preference:
            matchExpressions:
              - key: kubernetes.io/arch
                operator: In
                values:
                  - arm64
        - weight: 50
          preference:
            matchExpressions:
              - key: computeClass
                operator: In
                values:
                  - general
        - weight: 10
          preference:
            matchExpressions:
              - key: storageClass
                operator: In
                values:
                  - network
  topologySpreadConstraints:
    - maxSkew: 1
      topologyKey: topology.kubernetes.io/zone
      whenUnsatisfiable: DoNotSchedule
      labelSelector:
        matchLabels:
          app.kubernetes.io/component: dashboard
          app.kubernetes.io/instance: goldilocks
      matchLabelKeys:
        - pod-template-hash
