apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: kafka-topics
  namespace: ${namespace}
spec:
  interval: 10m
  timeout: 5m
  chart:
    spec:
      chart: logscale-strimzi-kafka-topics
      version: "3.0.0"
      sourceRef:
        kind: HelmRepository
        name: logscale-contrib
        namespace: flux-system
      interval: 5m
  releaseName: kafka-topics
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  test:
    enable: false
  driftDetection:
    mode: enabled
    ignore:
      - paths: ["/spec/replicas"]
        target:
          kind: Deployment
  dependsOn:
    - name: kafka
  values:
    fullnameOverride: logscale-topics
    config:
      clusterName: kafka
      prefix: g000
