apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: ${tenant}-logscale
  namespace: ${kafka_namespace}
spec:
  interval: 10m
  timeout: 5m
  chart:
    spec:
      chart: logscale-strimzi-kafka-topics
      version: "3.0.0-next.3"
      sourceRef:
        kind: HelmRepository
        name: logscale-contrib
        namespace: flux-system
      interval: 5m
  releaseName: ${tenant}-logscale
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  test:
    enable: false
  driftDetection:
    mode: enabled
  dependsOn:
    - name: kafka
  values:
    config:
      clusterName: ${kafkaCluster}
      prefix: ${prefix}
